# Generated by Django 6.0.3 on 2026-04-06 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceCode',
            fields=[
                ('hash_id', models.CharField(editable=False, help_text='Mã băm SHA-256 của nội dung code gốc', max_length=64, primary_key=True, serialize=False)),
                ('compressed_content', models.BinaryField(help_text='Dữ liệu code đã nén bằng zlib')),
            ],
            options={
                'db_table': 'source_code',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to=settings.AUTH_USER_MODEL)),
                ('code_ref', models.ForeignKey(db_column='code_ref', on_delete=django.db.models.deletion.PROTECT, related_name='associated_lessons', to='lesson.sourcecode')),
            ],
            options={
                'db_table': 'lesson',
            },
        ),
    ]
