# Generated by Django 6.0.3 on 2026-04-06 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_managers_remove_user_full_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersession',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='usersession',
            name='is_revoked',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='refresh_token',
            field=models.CharField(db_index=True, max_length=512, unique=True),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
