# Generated by Django 6.0.3 on 2026-04-09 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_usersession_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
