# Generated by Django 6.0.3 on 2026-04-09 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_usersession_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersession',
            name='refresh_token',
            field=models.TextField(db_index=True, unique=True),
        ),
    ]
