# Generated by Django 6.0.3 on 2026-04-09 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_usersession_refresh_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersession',
            name='refresh_token',
            field=models.CharField(db_index=True, max_length=512, unique=True),
        ),
    ]
