# Generated by Django 6.0.3 on 2026-04-13 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_user_is_email_verified_user_is_phone_verified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersession',
            name='last_activity',
        ),
    ]
